//
//  PostCreateAction+ScriptGenerator.swift
//  aizen
//

import Foundation

// MARK: - Script Generator

nonisolated struct PostCreateScriptGenerator {

    /// Generates a bash script from actions
    /// - Parameters:
    ///   - actions: List of actions to convert to script
    ///   - mainWorktreePath: Path to main worktree (available as $MAIN)
    ///   - newWorktreePath: Path to new worktree (available as $NEW)
    /// - Returns: Generated bash script
    static func generateScript(from actions: [PostCreateAction]) -> String {
        let enabledActions = actions.filter { $0.enabled }
        guard !enabledActions.isEmpty else { return "" }

        var lines: [String] = [
            "#!/bin/bash",
            "set -e",
            "",
            "# Post-create script generated by Aizen",
            "# $1 = new worktree path",
            "# $2 = main worktree path",
            "",
            "NEW=\"$1\"",
            "MAIN=\"$2\"",
            ""
        ]

        for action in enabledActions {
            lines.append(contentsOf: generateActionScript(action))
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private static func generateActionScript(_ action: PostCreateAction) -> [String] {
        switch action.config {
        case .copyFiles(let config):
            return generateCopyFilesScript(config)
        case .runCommand(let config):
            return generateRunCommandScript(config)
        case .symlink(let config):
            return generateSymlinkScript(config)
        case .customScript(let config):
            return generateCustomScript(config)
        }
    }

    private static func generateCopyFilesScript(_ config: CopyFilesConfig) -> [String] {
        var lines = ["# Copy files from main worktree"]

        for pattern in config.patterns {
            if pattern.contains("*") {
                // Glob pattern - use find and cp
                let escapedPattern = pattern.replacingOccurrences(of: "\"", with: "\\\"")
                lines.append("find \"$MAIN\" -path \"$MAIN/\(escapedPattern)\" -exec cp -r {} \"$NEW/\" \\; 2>/dev/null || true")
            } else {
                // Simple file/directory - direct copy
                lines.append("[ -e \"$MAIN/\(pattern)\" ] && cp -r \"$MAIN/\(pattern)\" \"$NEW/\" 2>/dev/null || true")
            }
        }

        return lines
    }

    private static func generateRunCommandScript(_ config: RunCommandConfig) -> [String] {
        let dir = config.workingDirectory == .newWorktree ? "$NEW" : "$MAIN"
        return [
            "# Run command: \(config.command)",
            "cd \"\(dir)\" && \(config.command)"
        ]
    }

    private static func generateSymlinkScript(_ config: SymlinkConfig) -> [String] {
        return [
            "# Create symlink: \(config.target) -> \(config.source)",
            "ln -sf \"$MAIN/\(config.source)\" \"$NEW/\(config.target)\""
        ]
    }

    private static func generateCustomScript(_ config: CustomScriptConfig) -> [String] {
        return [
            "# Custom script",
            config.script
        ]
    }
}
