import Foundation

extension Ghostty.Input.Key {
    // Based on src/input/keycodes.zig
    var keyCode: UInt16? {
        switch self {
        case .backquote: return 0x0032
        case .backslash: return 0x002a
        case .bracketLeft: return 0x0021
        case .bracketRight: return 0x001e
        case .comma: return 0x002b
        case .digit0: return 0x001d
        case .digit1: return 0x0012
        case .digit2: return 0x0013
        case .digit3: return 0x0014
        case .digit4: return 0x0015
        case .digit5: return 0x0017
        case .digit6: return 0x0016
        case .digit7: return 0x001a
        case .digit8: return 0x001c
        case .digit9: return 0x0019
        case .equal: return 0x0018
        case .intlBackslash: return 0x000a
        case .intlRo: return 0x005e
        case .intlYen: return 0x005d
        case .a: return 0x0000
        case .b: return 0x000b
        case .c: return 0x0008
        case .d: return 0x0002
        case .e: return 0x000e
        case .f: return 0x0003
        case .g: return 0x0005
        case .h: return 0x0004
        case .i: return 0x0022
        case .j: return 0x0026
        case .k: return 0x0028
        case .l: return 0x0025
        case .m: return 0x002e
        case .n: return 0x002d
        case .o: return 0x001f
        case .p: return 0x0023
        case .q: return 0x000c
        case .r: return 0x000f
        case .s: return 0x0001
        case .t: return 0x0011
        case .u: return 0x0020
        case .v: return 0x0009
        case .w: return 0x000d
        case .x: return 0x0007
        case .y: return 0x0010
        case .z: return 0x0006
        case .minus: return 0x001b
        case .period: return 0x002f
        case .quote: return 0x0027
        case .semicolon: return 0x0029
        case .slash: return 0x002c
        case .altLeft: return 0x003a
        case .altRight: return 0x003d
        case .backspace: return 0x0033
        case .capsLock: return 0x0039
        case .contextMenu: return 0x006e
        case .controlLeft: return 0x003b
        case .controlRight: return 0x003e
        case .enter: return 0x0024
        case .metaLeft: return 0x0037
        case .metaRight: return 0x0036
        case .shiftLeft: return 0x0038
        case .shiftRight: return 0x003c
        case .space: return 0x0031
        case .tab: return 0x0030
        case .convert: return nil
        case .kanaMode: return nil
        case .nonConvert: return nil
        case .delete: return 0x0075
        case .end: return 0x0077
        case .help: return nil
        case .home: return 0x0073
        case .insert: return 0x0072
        case .pageDown: return 0x0079
        case .pageUp: return 0x0074
        case .arrowDown: return 0x007d
        case .arrowLeft: return 0x007b
        case .arrowRight: return 0x007c
        case .arrowUp: return 0x007e
        case .numLock: return 0x0047
        case .numpad0: return 0x0052
        case .numpad1: return 0x0053
        case .numpad2: return 0x0054
        case .numpad3: return 0x0055
        case .numpad4: return 0x0056
        case .numpad5: return 0x0057
        case .numpad6: return 0x0058
        case .numpad7: return 0x0059
        case .numpad8: return 0x005b
        case .numpad9: return 0x005c
        case .numpadAdd: return 0x0045
        case .numpadBackspace: return nil
        case .numpadClear: return nil
        case .numpadClearEntry: return nil
        case .numpadComma: return 0x005f
        case .numpadDecimal: return 0x0041
        case .numpadDivide: return 0x004b
        case .numpadEnter: return 0x004c
        case .numpadEqual: return 0x0051
        case .numpadMemoryAdd: return nil
        case .numpadMemoryClear: return nil
        case .numpadMemoryRecall: return nil
        case .numpadMemoryStore: return nil
        case .numpadMemorySubtract: return nil
        case .numpadMultiply: return 0x0043
        case .numpadParenLeft: return nil
        case .numpadParenRight: return nil
        case .numpadSubtract: return 0x004e
        case .numpadSeparator: return nil
        case .numpadUp: return nil
        case .numpadDown: return nil
        case .numpadRight: return nil
        case .numpadLeft: return nil
        case .numpadBegin: return nil
        case .numpadHome: return nil
        case .numpadEnd: return nil
        case .numpadInsert: return nil
        case .numpadDelete: return nil
        case .numpadPageUp: return nil
        case .numpadPageDown: return nil
        case .escape: return 0x0035
        case .f1: return 0x007a
        case .f2: return 0x0078
        case .f3: return 0x0063
        case .f4: return 0x0076
        case .f5: return 0x0060
        case .f6: return 0x0061
        case .f7: return 0x0062
        case .f8: return 0x0064
        case .f9: return 0x0065
        case .f10: return 0x006d
        case .f11: return 0x0067
        case .f12: return 0x006f
        case .f13: return 0x0069
        case .f14: return 0x006b
        case .f15: return 0x0071
        case .f16: return 0x006a
        case .f17: return 0x0040
        case .f18: return 0x004f
        case .f19: return 0x0050
        case .f20: return 0x005a
        case .f21: return nil
        case .f22: return nil
        case .f23: return nil
        case .f24: return nil
        case .f25: return nil
        case .fn: return nil
        case .fnLock: return nil
        case .printScreen: return nil
        case .scrollLock: return nil
        case .pause: return nil
        case .browserBack: return nil
        case .browserFavorites: return nil
        case .browserForward: return nil
        case .browserHome: return nil
        case .browserRefresh: return nil
        case .browserSearch: return nil
        case .browserStop: return nil
        case .eject: return nil
        case .launchApp1: return nil
        case .launchApp2: return nil
        case .launchMail: return nil
        case .mediaPlayPause: return nil
        case .mediaSelect: return nil
        case .mediaStop: return nil
        case .mediaTrackNext: return nil
        case .mediaTrackPrevious: return nil
        case .power: return nil
        case .sleep: return nil
        case .audioVolumeDown: return 0x0049
        case .audioVolumeMute: return 0x004a
        case .audioVolumeUp: return 0x0048
        case .wakeUp: return nil
        case .copy: return nil
        case .cut: return nil
        case .paste: return nil
        }
    }
}
